### ISSUE TITLE
ArrayIndexOutOfBoundsException ：1 

### ISSUE THREAD

**Issue by FortuneDream** [bytedance/ByteX#103]
我自己的项目外部依赖0.1.8版本。
将master分支上的MethodCallOptPlugin相关代码移植到自己的Transform流程上后，在**其他插件**上会出现这个错误。
at org.objectweb.asm.ClassReader$accept.call(Unknow Source)
at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
at org.objectweb.asm.ClassReader.aceept(ClassReader.java:542)

确认出问题的transform是在执行了MethodCallOptPlugin的Transform之后才有的。
感觉是不是MethodCallOptPlugin的字节码处理有点问题？不然为啥会越界异常呢？

**Comment by yangzhiqian** [comment]
信息有点少啊，处理如果有问题，可以对比一下处理前后的字节码，这个应该好分析。
