### ISSUE TITLE
java.lang.UnsupportedOperationException: This feature requires ASM6

### ISSUE THREAD

**Issue by xmqapple** [bytedance/ByteX#104]
java.lang.UnsupportedOperationException: This feature requires ASM6
        at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:130)
        at org.objectweb.asm.ClassReader.readModuleAttributes(ClassReader.java:724)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:544)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
        at com.ss.android.ugc.bytex.common.visitor.ClassVisitorChain.accept(ClassVisitorChain.java:55)
        at com.ss.android.ugc.bytex.common.processor.ClassFileAnalyzer.handle(ClassFileAnalyzer.java:91)
        at com.ss.android.ugc.bytex.transformer.processor.ClassFileProcessor.process(ClassFileProcessor.java:27)
        at com.ss.android.ugc.bytex.transformer.processor.ProcessorChain.proceed(ProcessorChain.java:30)
        at com.ss.android.ugc.bytex.transformer.processor.FilterFileProcessor.process(FilterFileProcessor.java:23)
        at com.ss.android.ugc.bytex.transformer.processor.ProcessorChain.proceed(ProcessorChain.java:30)
        at com.ss.android.ugc.bytex.transformer.processor.task.TraverseTask.compute(TraverseTask.java:31)
        at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:396)
        at java.base/java.util.concurrent.ForkJoinTask.invokeAll(ForkJoinTask.java:853)
        at com.ss.android.ugc.bytex.transformer.processor.task.FileTraverseTask.compute(FileTraverseTask.java:40)
        at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by yangzhiqian** [comment]
bytex版本确认一下?最新版应该没有这个问题。

**Comment by yangzhiqian** [comment]
内部已经验证这个没有问题，后续有反馈再打开
