### ISSUE TITLE
shrink_r_class导致第三方人脸识别报错 NoClassDefFoundError

### ISSUE THREAD

**Issue by xmqapple** [bytedance/ByteX#107]
Process: com.kubi.kucoin, PID: 15856
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/alibaba/security/biometrics/R$drawable;
        at com.alibaba.security.biometrics.activity.BaseBioNavigatorActivity.onCreate(BaseBioNavigatorActivity.java:8)
        at com.alibaba.security.biometrics.activity.ALBiometricsActivity.onCreate(ALBiometricsActivity.java:1)
        at android.app.Activity.performCreate(Activity.java:7893)
        at android.app.Activity.performCreate(Activity.java:7880)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3287)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3461)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2048)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7582)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
     Caused by: java.lang.ClassNotFoundException: com.alibaba.security.biometrics.R$drawable
        at com.alibaba.security.biometrics.activity.BaseBioNavigatorActivity.onCreate(BaseBioNavigatorActivity.java:8) 
        at com.alibaba.security.biometrics.activity.ALBiometricsActivity.onCreate(ALBiometricsActivity.java:1) 
        at android.app.Activity.performCreate(Activity.java:7893) 
        at android.app.Activity.performCreate(Activity.java:7880) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3287) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3461) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2048) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:227) 
        at android.app.ActivityThread.main(ActivityThread.java:7582) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)

**Comment by yangzhiqian** [comment]
看一下是不是反射调用，反射调用那需要单独加白。如果不是，确认一下资源是否存在(因为资源不存在appt打包时对应的R中不会有这个id)
