### ISSUE TITLE
java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by m18664920330** [bytedance/ByteX#46]
继承BaseClassVisitor实现插件 
调用插件的时候报异常java.lang.UnsupportedOperationException
	at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:135)
	at org.objectweb.asm.ClassReader.readModule(ClassReader.java:715)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:536)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
相应的提示代码
if (api < Opcodes.ASM6) {
      throw new UnsupportedOperationException();
    }
为什么BaseClassVisitor的构造方法里要使用Opcodes.ASM5？

**Comment by yangzhiqian** [comment]
刚开始的时候绝大部分字节码都在java6、7、8的版本，当时就使用了ASM5，没有考虑到java9的版本，，对于使用java9的库会报错，已知的gson2.8.6是有不兼容的。这个已经加入到todo中了。

**Comment by Zweihui** [comment]
我也遇到这个问题了 希望能快点解决

**Comment by yangzhiqian** [comment]
0.2.3已经全部切到ASM6
